TeamFAST - Frontend: Recipient Class Reference
Recipient Class Reference
Public Member Functions
constructor (props)
componentDidMount ()
refreshRecipients ()
handleRecipientDelete (e, r)
handleSearch (e)
get_languages (languages_list)
capitalize (str)
get_phone (phone)
readFile (event)
Detailed Description
This component is used to display recipient information on the application's Data page.
Member Function Documentation
componentDidMount()
Recipient::componentDidMount () inline
Life cycle hook that is called after the component is first rendered.
constructor()
Recipient::constructor (props) inline
The constructor method initializes the component's state object and binds the methods of the component to the current instance.
Parameters
{Object} props The properties passed to the component.
References handleRecipientDelete(), and handleSearch().
handleRecipientDelete()
Recipient::handleRecipientDelete (e, r) inline
Event handler used to delete a recipient from the database when the user clicks on the delete button.
Parameters
{Object} e The event triggered when the user clicks on the q Delete button.
{Object} r The recipient object to be deleted.
Referenced by constructor().
handleSearch()
Recipient::handleSearch (e) inline
Event handler method called when the user enters a value into the recipient search box.
Parameters
{Object} e The event triggered when a user enters information into the search field.
Referenced by constructor().
The documentation for this class was generated from the following file:
frontend/src/components/Data/Recipient/Recipient.js