TeamFAST - Frontend: RouteResults Class Reference
RouteResults Class Reference
Public Member Functions
constructor (props)
componentDidMount ()
getRecipientName (recipient)
getMissingName (id)
getMissingAddress (id)
getMissingPhone (id)
getPhone (recipient)
getDriverName (route)
getCapacity (route)
getEmployeeStatus (route)
render ()
Detailed Description
This component is used to display route information for all selected drivers with links to view individual route information.
Member Function Documentation
componentDidMount()
RouteResults::componentDidMount () inline
Life cycle hook that is called after the component is first rendered.
constructor()
RouteResults::constructor (props) inline
The constructor method initializes the component's state object and binds the methods of the component to the current instance.
Parameters
{Object} props The properties passed to the component.
References getCapacity(), getDriverName(), getEmployeeStatus(), getMissingAddress(), getMissingName(), getMissingPhone(), getPhone(), and getRecipientName().
getCapacity()
RouteResults::getCapacity (route) inline
Function to return capacity for individual drivers. Called for each driver in the route list.
Parameters
{Object} route Route object from the route list.
Returns
Driver's capacity.
Referenced by constructor(), and render().
getDriverName()
RouteResults::getDriverName (route) inline
Function to return full name for individual drivers. Called for each driver in the route list.
Parameters
{Object} route Route object from the route list.
Returns
Driver's full name.
Referenced by constructor(), and render().
getEmployeeStatus()
RouteResults::getEmployeeStatus (route) inline
Function to return employee staus for individual drivers. Called for each driver in the route list.
Parameters
{Object} route Route object from the route list.
Returns
Driver's employee status.
Referenced by constructor(), and render().
getMissingAddress()
RouteResults::getMissingAddress (id) inline
Function to return address for missing recipients. Called for each client that is missing from the route list.
Parameters
{Number} id Recipient id from the missing list.
Returns
Client's address.
Referenced by constructor(), and render().
getMissingName()
RouteResults::getMissingName (id) inline
Function to return full name for missing recipients. Called for each client that is missing from the route list.
Parameters
{Number} id Recipient id from the missing list.
Returns
Client's full name.
Referenced by constructor(), and render().
getMissingPhone()
RouteResults::getMissingPhone (id) inline
Function to return phone number for missing recipients. Called for each client that is missing from the route list.
Parameters
{Number} id Recipient id from the missing list.
Returns
Client's phone number.
Referenced by constructor(), and render().
getPhone()
RouteResults::getPhone (recipient) inline
Function to return phone number for individual recipients. Called for each client in the itinerary for each driver's route.
Parameters
{Object} recipient Recipient object from the route.
Returns
Client's phone number.
Referenced by constructor(), and render().
getRecipientName()
RouteResults::getRecipientName (recipient) inline
Function to return full name for individual recipients. Called for each client in the itinerary for each driver's route.
Parameters
{Object} recipient Recipient object from the route.
Returns
Client's full name.
Referenced by constructor(), and render().
render()
RouteResults::render () inline
The render method used to display the component.
Returns
The HTML to be rendered.
References getCapacity(), getDriverName(), getEmployeeStatus(), getMissingAddress(), getMissingName(), getMissingPhone(), getPhone(), and getRecipientName().
The documentation for this class was generated from the following file:
frontend/src/components/Route_Results/RouteResults.js