TeamFAST - Frontend: UpdateDriver Class Reference
UpdateDriver Class Reference
Public Member Functions
constructor (props)
componentDidMount ()
getEventValue (event)
getEventName (event)
getEventID (event)
handleAvailabilityChange (event)
handleLanguageChange (event)
handleChange (event)
handlePhoneChange (event)
Detailed Description
This component is used to update individual driver information stored in the database.
Member Function Documentation
componentDidMount()
UpdateDriver::componentDidMount () inline
Life cycle hook that is called after the component is first rendered.
constructor()
UpdateDriver::constructor (props) inline
The constructor method initializes the component's state object and binds the methods of the component to the current instance.
Parameters
{Object} props The properties passed to the component.
References getEventID(), getEventName(), getEventValue(), handleAvailabilityChange(), handleChange(), handleLanguageChange(), and handlePhoneChange().
getEventID()
UpdateDriver::getEventID (event) inline
This method retrieves the id property of the event that has been triggered.
Parameters
{Object} event The event that has been triggered.
Returns
The id property of the triggered event.
Referenced by constructor(), handleAvailabilityChange(), and handleLanguageChange().
getEventName()
UpdateDriver::getEventName (event) inline
This method retrieves the name property of the event that has been triggered.
Parameters
{Object} event The event that has been triggered.
Returns
The name property of the triggered event.
Referenced by constructor(), handleAvailabilityChange(), and handleChange().
getEventValue()
UpdateDriver::getEventValue (event) inline
This method retrieves the value property of the event that has been triggered.
Parameters
{Object} event The event that has been triggered.
Returns
The value property of the triggered event.
Referenced by constructor(), and handleChange().
handleAvailabilityChange()
UpdateDriver::handleAvailabilityChange (event) inline
Event handler that is called to update the component's state when the user changes the values of the form fields associated with a driver's availability.
Parameters
{Object} event The event that is triggered on a change of value to the availability fields in the form.
References getEventID(), and getEventName().
Referenced by constructor().
handleChange()
UpdateDriver::handleChange (event) inline
Generic event handler that is called to update the component's state when the user changes the value of a form field that does not require special handling.
Parameters
{Object} event The event that is triggered on a change of value to a generic form field.
References getEventName(), and getEventValue().
Referenced by constructor().
handleLanguageChange()
UpdateDriver::handleLanguageChange (event) inline
Event handler that is called to update the component's state when the user changes the values of the form fields associated with a driver's languages.
Parameters
{Object} event The event that is triggered on a change of value to the language fields in the form.
References getEventID().
Referenced by constructor().
handlePhoneChange()
UpdateDriver::handlePhoneChange (event) inline
Event handler that is called to update the component's state when the user changes the value of the form field associated with a driver's phone number.
Parameters
{Object} event The event that is triggered on a change of value to the phone number field in the form.
Referenced by constructor().
The documentation for this class was generated from the following file:
frontend/src/components/Data/Driver/UpdateDriver.js