TeamFAST - Frontend: DriverRoute Class Reference
DriverRoute Class Reference
Public Member Functions
constructor (props)
componentDidMount ()
getRecipientName (recipient)
getPhone (recipient)
render ()
Detailed Description
This component is used to display route information for an individual driver.
Member Function Documentation
componentDidMount()
DriverRoute::componentDidMount () inline
Life cycle hook that is called after the component is first rendered.
constructor()
DriverRoute::constructor (props) inline
The constructor method initializes the component's state object and binds the methods of the component to the current instance.
Parameters
{Object} props The properties passed to the component.
References getPhone(), and getRecipientName().
getPhone()
DriverRoute::getPhone (recipient) inline
Function to return phone number for individual recipients. Called for each client in the itinerary for the driver's route.
Parameters
{Object} recipient Recipient object from the route.
Returns
Client's phone number.
Referenced by constructor(), and render().
getRecipientName()
DriverRoute::getRecipientName (recipient) inline
Function to return full name for individual recipients. Called for each client in the itinerary for each driver's route.
Parameters
{Object} recipient Recipient object from the route.
Returns
Client's full name.
Referenced by constructor(), and render().
render()
DriverRoute::render () inline
The render method used to display the component.
Returns
The HTML to be rendered.
References getPhone(), and getRecipientName().
The documentation for this class was generated from the following file:
frontend/src/components/Route_Results/DriverRoute.js