TeamFAST - Frontend: ViewDriver Class Reference
ViewDriver Class Reference
Public Member Functions
constructor (props)
componentDidMount ()
showLanguages ()
showAvailability ()
render ()
Detailed Description
This component is used to view individual driver information stored in the database.
Member Function Documentation
componentDidMount()
ViewDriver::componentDidMount () inline
Life cycle hook that is called after the component is first rendered.
constructor()
ViewDriver::constructor (props) inline
The constructor method initializes the component's state object and binds the methods of the component to the current instance.
Parameters
{Object} props The properties passed to the component.
References showAvailability(), and showLanguages().
render()
ViewDriver::render () inline
The render method used to display the component.
Returns
The HTML to be rendered.
References showAvailability(), and showLanguages().
showAvailability()
ViewDriver::showAvailability () inline
Method to map the availability object stored in the component's state to a list of strings denoting a driver's availability for each day of the week..
Returns
The list of the driver's availability for each day of the week.
Referenced by constructor(), and render().
showLanguages()
ViewDriver::showLanguages () inline
Method to map the array of language objects stored in the component's state to a list of language names.
Returns
The list of language names for the driver.
Referenced by constructor(), and render().
The documentation for this class was generated from the following file:
frontend/src/components/Data/Driver/ViewDriver.js