TeamFAST - Frontend: Driver Class Reference
Driver Class Reference
Public Member Functions
constructor (props)
componentDidMount ()
refreshDrivers ()
handleDriverDelete (e, d)
get_availability (availability_list)
handleSearch (e)
get_phone (phone)
capitalize (str)
get_languages (languages_list)
readFile (event)
render ()
Detailed Description
This component is used to display driver information on the application's Data page.
Member Function Documentation
componentDidMount()
Driver::componentDidMount () inline
Life cycle hook that is called after the component is first rendered.
constructor()
Driver::constructor (props) inline
The constructor method initializes the component's state object and binds the methods of the component to the current instance.
Parameters
{Object} props The properties passed to the component.
References handleDriverDelete(), and handleSearch().
handleDriverDelete()
Driver::handleDriverDelete (e, d) inline
Event handler used to delete a driver from the database when the user clicks on the delete button.
Parameters
{Object} e The event triggered when the user clicks on the q Delete button.
{Object} d The driver object to be deleted.
Referenced by constructor(), and render().
handleSearch()
Driver::handleSearch (e) inline
Event handler method called when the user enters a value into the driver search box.
Parameters
{Object} e The event triggered when a user enters information into the search field.
Referenced by constructor(), and render().
render()
Driver::render () inline
The render method used to display the component.
Returns
The HTML to be rendered.
References handleDriverDelete(), and handleSearch().
The documentation for this class was generated from the following file:
frontend/src/components/Data/Driver/Driver.js